# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'ipaddr'
require 'yaml'

$vars = YAML::load_file('pipeline.yml')
$provider = $vars['provider']['type']['openstack']
$nodes = $vars['hosts']
$ansible_groups = {}
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty64"
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = $provider['private_key_path'].to_s 
  
  
  j = 1
  $nodes.each_pair do |node, opts|
    $ansible_groups[node]=[]
    (1..opts['count']).each do |i|
      hostname = "#{opts['hostname_prefix']}#{node}#{i}"
      if hostname.include? "_"
        hostname["_"] = "-"
      end

      $ansible_groups[node] << hostname


      config.vm.define hostname.to_sym do |node_conf|
      
      node_conf.vm.provider "openstack" do |os|
        os.ssh_timeout        = 300
        os.openstack_auth_url = $provider['endpoint'].to_s
        os.username           = $provider['username'].to_s
        os.password           = $provider['password'].to_s
        os.tenant_name        = $provider['tenant'].to_s
        os.flavor             = opts["provider"]["openstack"]['flavor'].to_s
        os.image              = opts["provider"]["openstack"]['image'].to_s
        os.floating_ip_pool   = opts["provider"]["openstack"]['floating_ip_pool'].to_s
        os.keypair_name       = $provider['keypair_name'].to_s
      end

        if node.equal? $nodes.to_a.last[0] and i.equal? opts['count']
          node_conf.vm.provision "ansible" do |ansible|
            ansible.playbook = "../../surge-playbooks/surge.yml"
            ansible.sudo = true
            ansible.limit = 'all'
            ansible.groups = $ansible_groups
            #ansible.verbose = 'vvvv'
          end
        end
      end
    end

  end


end