---
# Surge pipeline SAMPLE FILE
# This provides Vagrant and ansible with all the info
# they need to deploy the pipeline

provider:
    type:
        #Common variables
        virtualbox:
            hostname_prefix: ""
            ip_start: 10.20.30.10

        docker:
            hostname_prefix: ""
            start_port: 8100

        openstack:
            endpoint: "<KEYSTONE_ENDPOINT>"
            username: <username>
            password: <password>
            tenant: <tenant>
            keypair_name: <keypair_name>
            networks: <network_id>
            private_key_path: <path_to_private_key>

hosts:
    zookeeper:
        count: 1
        provider:
            virtualbox:
                memory: 1024
            openstack:
                flavor: m1.medium
                image: ubuntu14.04
                floating_ip_pool: public-net


    kafka:
        count: 1
        provider:
            virtualbox:
                memory: 2048
            openstack:
                flavor: m1.medium
                image: ubuntu14.04
                floating_ip_pool: public-net
        #To be supported soon
        # configuration:
            # controlled.shutdown.enable: true
            # log.roll.hours: 48
            # log.retention.hours: 48
            # auto.create.topics.enable: true
            # kafka_heap_opts: '-Xms512M -Xmx512M -XX:NewSize=200m -XX:MaxNewSize=200m'
            # kafka_opts: '-XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintTenuringDistribution'
            # limits_manage: true
            # limits_nofile: 65536
            # num.network.threads: 3

    storm-nimbus:
        count: 1
        provider:
            virtualbox:
                memory: 1024
                forwarded_ports:
                    - guest: 8080
                      host: 28080
            openstack:
                flavor: m1.medium
                image: ubuntu14.04
                floating_ip_pool: public-net

    storm-supervisor:
        count: 1
        provider:
            virtualbox:
                memory: 1024
            openstack:
                flavor: m1.medium
                image: ubuntu14.04
                floating_ip_pool: public-net


