---
# Surge pipeline SAMPLE FILE
# This provides Vagrant and ansible with all the info
# they need to deploy the pipeline

provider:
    type:
        #Common variables
        virtualbox:
            hostname_prefix: ""
            ip_start: 10.20.30.10

        openstack:
            endpoint: "http://172.16.91.150:5000/v2.0/tokens"
            username: admin
            password: "1"
            tenant: "admin"
            keypair_name: vagrant
            private_key_path: "/Users/msolanas/Downloads/vagrant.pem"

hosts:
    zookeeper:
        count: 1
        provider:
            virtualbox:
                memory: 1024
            openstack:
                flavor: m1.medium
                image: ubuntu
                floating_ip_pool: public


    kafka:
        count: 2
        provider:
            virtualbox:
                memory: 2048
            openstack:
                flavor: m1.medium
                image: ubuntu
                floating_ip_pool: public
        #To be supported soon
        # configuration:
            # controlled.shutdown.enable: true
            # log.roll.hours: 48
            # log.retention.hours: 48
            # auto.create.topics.enable: true
            # kafka_heap_opts: '-Xms512M -Xmx512M -XX:NewSize=200m -XX:MaxNewSize=200m'
            # kafka_opts: '-XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintTenuringDistribution'
            # limits_manage: true
            # limits_nofile: 65536
            # num.network.threads: 3

    # storm-nimbus:
    #     count: 1
    #     provider:
    #         virtualbox:
    #             memory: 1024
    #             ip_start: 10.20.30.120
    #             forwarded_ports:
    #                 - guest: 8080
    #                   host: 28080
    #         openstack:
    #             flavor: m1.medium
                # image: ubuntu
                # floating_ip_pool: public

    # storm-supervisor:
    #     count: 2
    #     provider:
    #         virtualbox:
    #             memory: 1024
    #             ip_start: 10.20.30.125
    #         openstack:
    #             flavor: m1.medium
                # image: ubuntu
                # floating_ip_pool: public


