# Config file for automatic testing at travis-ci.org
language: python

sudo: false

matrix:
  fast_finish: true

install: 
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
    - tox
