

# Copyright 2015 Cisco Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Creating supervisord's script
  template: src=storm-nimbus.conf.j2 dest=/etc/supervisor/conf.d/storm-nimbus.conf owner=root group=root mode=0644

- name: Running Supervisor Docker Dependency
  shell: supervisord
  ignore_errors: yes

- name: Ensuring supervisord finds it
  supervisorctl: name=storm-nimbus state=present

- name: Restarting Storm-nimbus
  supervisorctl: name=storm-nimbus state=restarted

- name: Creating supervisord's script
  template: src=storm-ui.conf.j2 dest=/etc/supervisor/conf.d/storm-ui.conf owner=root group=root mode=0644

- name: Ensuring supervisord finds it
  supervisorctl: name=storm-ui state=present

- name: Restarting Storm-ui
  supervisorctl: name=storm-ui state=restarted
