

# Copyright 2015 Cisco Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Installing dependencies
  apt: pkg={{ item }}
  with_items:
    - libtool
  sudo: yes

- name: Cloning JZMQ
  git: repo=https://github.com/nathanmarz/jzmq dest=/tmp/jzmq

- name: Autogenerating JZMQ
  command: ./autogen.sh chdir=/tmp/jzmq

- name: Creating classdist_noinst.stamp
  command: touch /tmp/jzmq/src/classdist_noinst.stamp

- name: Redefining class path
  shell: CLASSPATH=.:./.:$CLASSPATH javac -d . org/zeromq/ZMQ.java org/zeromq/ZMQException.java org/zeromq/ZMQQueue.java org/zeromq/ZMQForwarder.java org/zeromq/ZMQStreamer.java chdir=/tmp/jzmq/src

- name: Autogenerating JZMQ again
  command: ./autogen.sh chdir=/tmp/jzmq

- name: Configuring JZMQ
  command: ./configure chdir=/tmp/jzmq
  environment:
        JAVA_HOME: /usr/local/java/jdk

- name: Compiling JZMQ
  command: sudo make chdir=/tmp/jzmq
  sudo: yes

- name: Installing JZMQ
  command: make install chdir=/tmp/jzmq
  sudo: yes